// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    Carousel: typeof import('./../components/Carousel/Carousel.vue')['default']
    CarouselDemo: typeof import('./../components/Carousel/CarouselDemo.vue')['default']
    CarouselItem: typeof import('./../components/Carousel/CarouselItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
  }
}
