// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    Carousel: typeof import('./../components/Carousel/Carousel.vue')['default']
    CarouselDemo: typeof import('./../components/Carousel/CarouselDemo.vue')['default']
    CarouselItem: typeof import('./../components/Carousel/CarouselItem.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    IconBlade: typeof import('./../components/IconBlade.vue')['default']
    ItemCard: typeof import('./../components/Item/ItemCard.vue')['default']
    ItemList: typeof import('./../components/Item/ItemList.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}
